### ISSUE TITLE
No output on page 

### ISSUE THREAD

**Issue by spawnazzo** [kkemple/tasker#52]
Hi there i've installed tasker on my macbook pro the installation says "done without errors"  the server it's started but actually cannot see any output on http://localhost:8888

![screen shot 2015-06-05 at 11 47 31](https://cloud.githubusercontent.com/assets/1212510/8003539/ba1e3ea6-0b78-11e5-999c-696cfb907910.png)

any hints? or logs? 

I also tried with {"id":1,"username":"myusername","password":"hashed_pwd","jiraUrl":"https://ticket.qxlricardo.com/","hasLoginCreds":true,"isVisible":false} 
no output

**Comment by spawnazzo** [comment]
solved by doing "bower install"

**Comment by kkemple** [comment]
:+1:

**Comment by kkemple** [comment]
@spawnazzo if you like tasker, i have a desktop version called Lumberjack I am working on that you can try out, let me know!

**Comment by spawnazzo** [comment]
that would be great but actually the authentication on my jira won't work with the webapp the decrypt function sees not working i'm going to open another issue
